// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIKUOy3PMRH8Cg3cAKvHZZumP8pzCHXGQ',
    appId: '1:105613704269:web:4d30c415cc8dd21476f004',
    messagingSenderId: '105613704269',
    projectId: 'didipartner-5caed',
    authDomain: 'didipartner-5caed.firebaseapp.com',
    storageBucket: 'didipartner-5caed.firebasestorage.app',
    measurementId: 'G-5M5BRV0MPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_T4f1mo4rUMiife5t96TnQ29vXhdW-5E',
    appId: '1:105613704269:android:e7c4fda1b6c9b04476f004',
    messagingSenderId: '105613704269',
    projectId: 'didipartner-5caed',
    storageBucket: 'didipartner-5caed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlunQ8u87OVqGcrekWT2wu-8Z2PPWpLk',
    appId: '1:105613704269:ios:46939c63768217ca76f004',
    messagingSenderId: '105613704269',
    projectId: 'didipartner-5caed',
    storageBucket: 'didipartner-5caed.firebasestorage.app',
    iosBundleId: 'com.example.didipartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnlunQ8u87OVqGcrekWT2wu-8Z2PPWpLk',
    appId: '1:105613704269:ios:46939c63768217ca76f004',
    messagingSenderId: '105613704269',
    projectId: 'didipartner-5caed',
    storageBucket: 'didipartner-5caed.firebasestorage.app',
    iosBundleId: 'com.example.didipartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIKUOy3PMRH8Cg3cAKvHZZumP8pzCHXGQ',
    appId: '1:105613704269:web:8a2c21873c01a8e176f004',
    messagingSenderId: '105613704269',
    projectId: 'didipartner-5caed',
    authDomain: 'didipartner-5caed.firebaseapp.com',
    storageBucket: 'didipartner-5caed.firebasestorage.app',
    measurementId: 'G-0DX18KCWGH',
  );
}
